### ISSUE TITLE
Loklak option's design on the settings panel is erroneous. 

### ISSUE THREAD

**Issue by sopankhosla** [loklak/loklak_php_api#35]
![selection_019](https://cloud.githubusercontent.com/assets/6399612/15934022/9aab8af8-2e7f-11e6-9b1e-8a43d4157f54.png)

**Comment by sopankhosla** [comment]
The fixed UI looks like this. 
![selection_020](https://cloud.githubusercontent.com/assets/6399612/15937321/06ea43b0-2e8c-11e6-97f0-b870849cab7c.png)
Considering that the usual settings options would look similar to the template in the example. The custom css file for loklak options could be directly included in the loklak_php_api package IMO.

**Comment by mariobehling** [comment]
Probably this should be added into the normal structure of plugins and use the css of each plugin instead of custom plugins. 

Please refer to this issue https://github.com/loklak/wp-twitter-widget/issues/8 about the UI for the plugin.

**Comment by mariobehling** [comment]
> Considering that the usual settings options would look similar to the template in the example. The custom css file for loklak options could be directly included in the loklak_php_api package IMO.

The css looks similar here, but maybe in other plugins it will not be similar. The plugin maintainer should have control of the looks and feel of their plugins without having to go to loklak related css to change that if they change the look of their plugin.

**Comment by sopankhosla** [comment]
@mariobehling The only change is to remove the <th> tags which are by default added as part of add_settings() function. Please see [this](https://github.com/loklak/loklak_php_api/commit/db482c1fa3b6f3fb6f1f8321234dcd65cd5c2581#diff-e35a207f683d325529db4b2c5c7fcd62R1)
So even if he wants to change the css it works perfectly fine. He will have full control of his plugin's CSS. he won't have to go to loklak related CSS for CSS changes in his settings as a whole.

**Comment by mariobehling** [comment]
ah ok. Sounds good in that case. Still in order to do the changes in the latest tweets plugin we need more changes as we have different headings etc.

**Comment by sopankhosla** [comment]
Yeah, If we want to have loklak settings before twitter settings, we need to include loklak options on top of the form and add a separate heading for loklak. I believe it would make sense to look into that once we have the updated API.
