### ISSUE TITLE
Set up Wordpress with Plugins on Heroku

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_php_api#39]
The goal of this is to have a wordpress setup including the plugins that can be continuously test.

**Comment by sopankhosla** [comment]
@mariobehling There is an online deployment of plugins. Please refer to https://still-badlands-77870.herokuapp.com/ . It is updated with all plugins I have worked on.

**Comment by sopankhosla** [comment]
Closing for now!

**Comment by mariobehling** [comment]
What is the access to this deployment? How can this be continuously tested? It is deployed from a repository?

**Comment by sopankhosla** [comment]
@mariobehling I had already sent the access username and password earlier. 
You have the admin access to this installation. Yes it is being deployed from a repo on my machine.

**Comment by mariobehling** [comment]
@sopu The goal is to deploy from a repo on GitHub and in the repo we should be able to add the latest version of apps. Is that feasible?

Deploying from your local machine does not really help us to make this sustainable.

**Comment by sopankhosla** [comment]
@mariobehling I could add the repo I am using to loklak repo and connect it to Heroku installation. I think it should work.

**Comment by sopankhosla** [comment]
I would be adding all plugins I developed, to [this](https://github.com/loklak/loklak_wordpress_plugins) repo. It is automatically deployed to Heroku. The link to deployed installation is https://still-badlands-77870.herokuapp.com/

**Comment by sopankhosla** [comment]
The repo is ready. It contains all plugins. Please refer to https://github.com/loklak/loklak_wordpress_plugins/tree/master/wp-content/plugins. 
Closing this issue for now. Since Heroku does not allow import of submodules from github repos, therefore complete plugin directories had to be added to repo.

**Comment by mariobehling** [comment]
Thanks, 
- [x] please use a more relevant subdomain e.g. loklak-wp.herokuapp...
- [x] Add Heroku badge, repo description and Wordpress version info in Readme.md
- [x] Add info how to update repo to a newer WP version in future
- [ ] Answer questions: Is it possible to have a demo login without risking anything in the service?

**Comment by sopankhosla** [comment]
@mariobehling 
- The new installation is http://loklak-wordpress.herokuapp.com. 
- Heroku badge, repo description and Wordpress version info has been added to Readme.md
- Wordpress update info has been added too. 
- I do not understand 
  
  > Answer questions: Is it possible to have a demo login without risking anything in the service?

[12a5754](https://github.com/loklak/loklak_wordpress_plugins/commit/12a57544421d6183dffc3acec574dac715f893ae) and  [d7b57dd](https://github.com/loklak/loklak_wordpress_plugins/commit/d7b57dd3c475b05edfa97ae70c611a07c4640736) adds it.

**Comment by mariobehling** [comment]
loklak-wordpress.herokuapp.com does not show the plugins currently.

> Answer questions: Is it possible to have a demo login without risking anything in the service?

How can I login? As an admin, a user etc?

How can we have a demo login for people to try out the plugins?

**Comment by mariobehling** [comment]
So, this issue is pretty old now. When can we see the plugins working in sample set up on the server?

**Comment by sopankhosla** [comment]
@mariobehling I have added a dummy login and sent credentials over Gitter. Since only an administrator level user can access, modify or configure plugins, therefore we cannot have a demo login with modification capabilities without risking the service.

**Comment by mariobehling** [comment]
@sopu If the service is deployed fresh, the plugins will not show up, correct? Could you add a script to enable and show the plugins at a fresh github to heroku deployment, please or outline another solution that does not require a user to login?

**Comment by sopankhosla** [comment]
@mariobehling: Please refer to https://github.com/loklak/loklak_php_api/issues/49#issuecomment-238145136

**Comment by sopankhosla** [comment]
Adding a dedicated issue for this. Closing it for now.
