### ISSUE TITLE
Document Plugins, Contact and Status

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_php_api#41]
There are a number of plugins available now, but the status is not always clear. Please provide an overview in a Plugins-Readme.md and include the following:
- [x] List of plugins
- [x] Name, contact, link to original maintainer
- [x] Date and version the plugin was taken
- [x] Description of Plugin functionality
- [x] Link to the GitHub loklak org repository
- [x] Link to plugin page on WP directory
- [x] Link to repository of plugin
- [x] What has been implemented and blockers
- [x] What is the status of the merge with the plugin author's version

**Comment by sopankhosla** [comment]
@mariobehling  On it!

**Comment by sopankhosla** [comment]
Adding plugin related information in [Plugins-readme.md](https://github.com/loklak/loklak_php_api/blob/master/Plugins-Readme.md)  
e988e6b

**Comment by sopankhosla** [comment]
4fafa17 completes the list. @mariobehling

**Comment by mariobehling** [comment]
Good job, but unfortunately there is still no loklak plugin on the wordpress directory. Such a pity!
