### ISSUE TITLE
Document plugins functionality and add screenshots to Readme.md

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_php_api#42]
A number of plugins with loklak are available now, but the info in Readme.md is limited in a number of plugins. Please add all relevant information about the WP plugins to the Readme.md and include screenshots.

**Comment by sopankhosla** [comment]
@mariobehling I have added screenshots and missing installation information to the respective plugin readme files. 
Could you please tell me if something else was supposed to be added in Readme files. If yes, then an example would help great deal. 
Thanx!

**Comment by sopankhosla** [comment]
I have documented the screenshots and installation information wherever I found important. Closing this issue for now!
