### ISSUE TITLE
Ensure only twitter is enabled as source and document feature

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_php_api#43]
loklak is currently expanding its source base. For the twitter plugins we should stay with twitter for the moment though. In future we could add options to cover other sources as well in the UI.

It is possible to limit loklak queries to a specific source. Please ensure and confirm all current WP plugins are limited to twitter as a source from loklak and document this feature in the relevant Readme.md's.

**Comment by sopankhosla** [comment]
@mariobehling I dont think I follow you correctly. When you say `source` do you mean the `source` attribute [here](http://loklak.org/api.html#search)?
So is the requirement of this issue to set `source=twitter` for all plugins?

**Comment by mariobehling** [comment]
Yes, correct.

**Comment by sopankhosla** [comment]
@mariobehling I currently see source change option in `Search` API. So adding it as an argument passed to search API function.

**Comment by sopankhosla** [comment]
@mariobehling Since all plugins use search API, I could document this feature in https://github.com/loklak/loklak_wordpress_plugins/blob/master/Plugin-Readme.md

**Comment by mariobehling** [comment]
Yes, please do. Thanks.

**Comment by sopankhosla** [comment]
[310cabf](https://github.com/loklak/loklak_wordpress_plugins/commit/310cabf89a58d129f1b1f3e035d13c8e9bb9be39) and 3835829 adds the documentation and feature respectively.

**Comment by sopankhosla** [comment]
Closing!
