### ISSUE TITLE
Request URL for localhost-only APIs should not be hard-coded in the functions

### ISSUE THREAD

**Issue by sopankhosla** [loklak/loklak_php_api#47]

**Comment by sopankhosla** [comment]
https://github.com/loklak/loklak_php_api/blob/master/loklak.php#L198 is hardcoded

**Comment by sopankhosla** [comment]
I guess that in order to test localhost - only APIs locally, we shouldn't have to set up two different connections. 
So it would be better if localhost URL is hardcoded for `account` and `settings` APIs

**Comment by sopankhosla** [comment]
@sudheesh001 we can't have travis CI test API functions which are localhost-only. Do you suggest a solution for it or should we keep it as is?

**Comment by sopankhosla** [comment]
@sudheesh001 ^ any ideas?

**Comment by sudheesh001** [comment]
we need to mock response i guess. https://github.com/InterNations/http-mock

**Comment by sopankhosla** [comment]
Opened #50 for this issue.

**Comment by sopankhosla** [comment]
PR merged! Added tests for localhost-based APIs. #50
