### ISSUE TITLE
Auto deployment and configuration of plugins to WP-Heroku installation

### ISSUE THREAD

**Issue by sopankhosla** [loklak/loklak_php_api#49]
Add a script to enable and show the plugins at a fresh github to heroku deployment
or 
Outline another solution that does not require a user to login?

**Comment by sopankhosla** [comment]
@mariobehling: Since plugins have some settings to be setup before configuration, so they wont show up when service is deployed fresh. 
I would try to come up with a solution.

> does not require a user to login?

Regarding this, if we are not allowing logins, then the person would only be able to see the output of plugins. He won't be able to test it as such by fiddling with e.g. number of tweets, add follow button etc options which are present in the settings of a plugin.

**Comment by mariobehling** [comment]
> Since plugins have some settings to be setup before configuration, so they wont show up when service is deployed fresh. 

Exactly and if we dont have anything to show there would be no point to have this deployment.

Therefore, please implement a script that runs during installation to activate the plugins and have some configuration enabled during installation.

**Comment by sopankhosla** [comment]
> the person would only be able to see the output of plugins. He won't be able to test it as such by fiddling with e.g. number of tweets, add follow button etc options which are present in the settings of a plugin.

@mariobehling

**Comment by mariobehling** [comment]
@sopu Yes, I understand, but this is already an improvement. Once the script is there, we should also add some basic articles in the deployment documenting the plugins and we need to think how to make a demo login, e.g. there could be a standard login and we make the password not changeable and a new deployment every 12 hours. Something like this would be nice, but let's go step by step. A site that shows all the plugins is a good first step.

**Comment by sopankhosla** [comment]
In order to show a particular state of the plugins, I will have to add default settings in plugins. And add there shortcode in 'Appearance' page. Currently approaching the issue with this mindset.

**Comment by mariobehling** [comment]
> default settings in plugins

Just to understand correctly. You are not changing the code of the plugins, but you are implementing "default settings" through a script with travis or how?

**Comment by sopankhosla** [comment]
- I am not sure if there is a way to bypass admin check and change plugin settings using a script. At some point (even if I try with cURL) the credentials would have to be compromised in order to reach the plugins. 
- For plugins which have configuration in their Appearance tab, it should be enough to just add a shortcode with default settings. Some of them are configured in settings and some in a different manner altogether.

@mariobehling

**Comment by sopankhosla** [comment]
I have added a new user role which implements above mentioned features. So Closing this issue for now!
