### ISSUE TITLE
loklak-php Structure organization

### ISSUE THREAD

**Issue by sudheesh001** [loklak/loklak_php_api#8]
Right now we have an `index.php` holding all the usages of the tests, A better way to do that would be to have a sample of each of these API's we have in a folder called `Examples` with the different files for each of the API's as an example. That makes it easier for the other developers using the system to quickly plugin the components they need into the system.

We also need to include unit tests into the PHP library, Maybe we could try PHPUnit https://phpunit.de/
We also need to lint the code with phplint so that the code quality is readable.
Integration of Travis CI for automated testing.

**Comment by sopankhosla** [comment]
+1 @sudheesh001 
Was thinking the same. 
Will work on it!

**Comment by sopankhosla** [comment]
Added travis integration and unit-tests!
